run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for this project
  
  gocyclo:
    min-complexity: 25  # Increased from 15
  
  goconst:
    min-len: 3
    min-occurrences: 5  # Increased from 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 140  # Increased from 120
  
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use standard library errors package"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - goconst
    - misspell
    - lll
    - goimports
    - gosec
  
  disable:
    - depguard      # Too strict for this project
    - gochecknoinits # Allow init functions
    - noctx         # Allow HTTP calls without context for CLI tool
    - stylecheck    # Too strict for this project
    - gocritic      # Too strict for this project

issues:
  exclude-dirs:
    - vendor
    - testdata
  
  exclude-files:
    - ".*_test.go"
  
  exclude-rules:
    - path: main.go
      linters:
        - gochecknoinits
    
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  
  max-issues-per-linter: 0
  max-same-issues: 0 